server:
  port: 8888

spring:
  application:
    name: wechat-component-web
  redis:
    database: 9
    host: 192.168.1.81
    port: 6379
    password: 123456
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456

wechat:
  appId: wx48cdbc777bc59a15
  appSecret: b494d62fad8cffa7355faa5e1ca906f7

